apiVersion: apps/v1
kind: Deployment
metadata:
    name: serveur-deployment
spec:
    replicas: 3
    selector:
      matchLabels:
         app: serveur
    template: 
      metadata:
         labels:
           app: serveur
      spec:
         containers: 
         - name: serveur
           image: hamzzza/node-redis:v2
           ports:
             - containerPort: 3000
             
apiVersion: v1
kind: Service
metadata:
  name: serveur-service
spec:
  selector:
    app: serveur
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer 
